name: StudyMinecraft
version: '1.0-SNAPSHOT'
main: fr.rosydev.studyminecraft.StudyMinecraft
api-version: '1.19'
authors: [C1ach0]
description: Plugin test
website: rosydev.fr
commands:
  test:
    description: Commande de test
  uwu:
    description: Commande uwu
  tpto:
    description: Ce tp à un joueur
    permission: staff